youDiedGif: /gif/you_died.gif
youDiedSound: /sound/you_died.wav
smallBonfireGif: /gif/bonfire_darksouls_small.gif
backgroundProgressBarGif: /gif/toxic_cloud.gif
dsOneSoundtrack: https://www.youtube.com/watch?v=iZ0Yp79Odl8&list=PLxh_0CD1_70Or5zVrJS7G5jWehpTzFNH6
dsTwoSoundtrack: https://www.youtube.com/watch?v=L0-SnILBhSQ&list=PLoGLTlImp5CbOC7yNc6XRavD06Gp-cqWR
dsThreeSoundtrack: https://www.youtube.com/watch?v=2EIuNCM1THI&list=PLlHY6e7WCV6M7UV1EBjAFA349aTyutIU4
eldenRingSoundtrack: https://www.youtube.com/watch?v=Vy_MyCbpDiQ&list=PLTmJuovQUxPuSYfrtCgpsLwQOeRXSkFzp
