customWidgetName: get some rest
settingsName: DarkSouls Progress Bar
dsPersistentTopicName: DSPersistentStateChanged
testFailureWindowDesc: Play animation on failed build
testFailureWindowName: TestFailureWindow
dsPluginConfigurableName: DSPluginConfigurable
